server:
  port: 9999

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/performance_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}